var HelpOBJ = require("./commands/help.js");
var ChestOBJ = require("./commands/chest.js");
var MachineOBJ = require("./commands/machine.js");
var SwitchOBJ = require("./commands/switch.js");
var PerksOBJ = require("./commands/perks.js");
var RoomsOBJ = require("./commands/rooms.js");
var WeaponsOBJ = require("./commands/weapons.js");
var ZombiesOBJ = require("./commands/zombies.js");
var VersionOBJ = require("./commands/version.js");

exports.help = HelpOBJ.helpCMD;
exports.chest = ChestOBJ.chestCMD;
exports.machine = MachineOBJ.machineCMD;
exports.switch = SwitchOBJ.switchCMD;
exports.perks = PerksOBJ.perksCMD;
exports.rooms = RoomsOBJ.roomsCMD;
exports.weapons = WeaponsOBJ.weaponsCMD;
exports.zombies = ZombiesOBJ.zombiesCMD;
exports.version = VersionOBJ.versionCMD;
